//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals:.
        /// </summary>
        public static string brojGolova {
            get {
                return ResourceManager.GetString("brojGolova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number:.
        /// </summary>
        public static string brojIgraca {
            get {
                return ResourceManager.GetString("brojIgraca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games tied:.
        /// </summary>
        public static string brojNeodlucenih {
            get {
                return ResourceManager.GetString("brojNeodlucenih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games played:.
        /// </summary>
        public static string brojOdigranihUtakmica {
            get {
                return ResourceManager.GetString("brojOdigranihUtakmica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games won:.
        /// </summary>
        public static string brojPobjeda {
            get {
                return ResourceManager.GetString("brojPobjeda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games lost:.
        /// </summary>
        public static string brojPoraza {
            get {
                return ResourceManager.GetString("brojPoraza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow cards:.
        /// </summary>
        public static string brojZutihKartona {
            get {
                return ResourceManager.GetString("brojZutihKartona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string btnDetalji {
            get {
                return ResourceManager.GetString("btnDetalji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting eleven.
        /// </summary>
        public static string btnNastavi {
            get {
                return ResourceManager.GetString("btnNastavi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string btnPostavke {
            get {
                return ResourceManager.GetString("btnPostavke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string btnPotvrdi {
            get {
                return ResourceManager.GetString("btnPotvrdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string detalji {
            get {
                return ResourceManager.GetString("detalji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home team.
        /// </summary>
        public static string domaciTim {
            get {
                return ResourceManager.GetString("domaciTim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string engleskiJezik {
            get {
                return ResourceManager.GetString("engleskiJezik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIFA code:.
        /// </summary>
        public static string fifaKod {
            get {
                return ResourceManager.GetString("fifaKod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal differential:.
        /// </summary>
        public static string golRazlika {
            get {
                return ResourceManager.GetString("golRazlika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest team.
        /// </summary>
        public static string gostTim {
            get {
                return ResourceManager.GetString("gostTim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        public static string hrvatskiJezik {
            get {
                return ResourceManager.GetString("hrvatskiJezik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string imeIgraca {
            get {
                return ResourceManager.GetString("imeIgraca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source:.
        /// </summary>
        public static string izvorPodataka {
            get {
                return ResourceManager.GetString("izvorPodataka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string jezik {
            get {
                return ResourceManager.GetString("jezik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain:.
        /// </summary>
        public static string kapetan {
            get {
                return ResourceManager.GetString("kapetan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Men.
        /// </summary>
        public static string muskoPrvenstvo {
            get {
                return ResourceManager.GetString("muskoPrvenstvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string nazivTima {
            get {
                return ResourceManager.GetString("nazivTima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position:.
        /// </summary>
        public static string pozicijaIgraca {
            get {
                return ResourceManager.GetString("pozicijaIgraca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player details.
        /// </summary>
        public static string pregledIgraca {
            get {
                return ResourceManager.GetString("pregledIgraca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals against:.
        /// </summary>
        public static string primljeniGolovi {
            get {
                return ResourceManager.GetString("primljeniGolovi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Championship:.
        /// </summary>
        public static string prvenstvo {
            get {
                return ResourceManager.GetString("prvenstvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution:.
        /// </summary>
        public static string rezolucija {
            get {
                return ResourceManager.GetString("rezolucija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals for:.
        /// </summary>
        public static string zabijeniGolovi {
            get {
                return ResourceManager.GetString("zabijeniGolovi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Women.
        /// </summary>
        public static string zenskoPrvenstvo {
            get {
                return ResourceManager.GetString("zenskoPrvenstvo", resourceCulture);
            }
        }
    }
}
